package pl.edu.agh.kis.encode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2021-05-05T07:20:42.560+02:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://kis.edu.agh.pl/", name = "ManageLogo")
@XmlSeeAlso({ObjectFactory.class})
public interface ManageLogo {

    @WebMethod(action = "upload")
    @RequestWrapper(localName = "upload", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.edu.agh.kis.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.edu.agh.kis.UploadResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.lang.String upload(

        @WebParam(name = "path", targetNamespace = "")
        java.lang.String path
    );

    @WebMethod(action = "download")
    @RequestWrapper(localName = "download", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.edu.agh.kis.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.edu.agh.kis.DownloadResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.lang.String download(

        @WebParam(name = "path", targetNamespace = "")
        java.lang.String path
    );
}
