package pl.edu.agh.kis.encode;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2021-05-05T07:20:42.653+02:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "ManageLogoService",
                  wsdlLocation = "http://localhost:8080/projektsoa-soap-api/ManageLogo?wsdl",
                  targetNamespace = "http://kis.edu.agh.pl/")
public class ManageLogoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://kis.edu.agh.pl/", "ManageLogoService");
    public final static QName ManageLogoPort = new QName("http://kis.edu.agh.pl/", "ManageLogoPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/projektsoa-soap-api/ManageLogo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ManageLogoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/projektsoa-soap-api/ManageLogo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ManageLogoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ManageLogoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageLogoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ManageLogoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ManageLogoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ManageLogoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ManageLogo
     */
    @WebEndpoint(name = "ManageLogoPort")
    public ManageLogo getManageLogoPort() {
        return super.getPort(ManageLogoPort, ManageLogo.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageLogo
     */
    @WebEndpoint(name = "ManageLogoPort")
    public ManageLogo getManageLogoPort(WebServiceFeature... features) {
        return super.getPort(ManageLogoPort, ManageLogo.class, features);
    }

}
