package pl.edu.agh.kis.show;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2021-05-05T05:16:37.927+02:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "ShowStudentsService",
                  wsdlLocation = "http://localhost:8080/projektsoa-soap-api/ShowStudents?wsdl",
                  targetNamespace = "http://kis.edu.agh.pl/")
public class ShowStudentsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://kis.edu.agh.pl/", "ShowStudentsService");
    public final static QName ShowStudentsPort = new QName("http://kis.edu.agh.pl/", "ShowStudentsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/projektsoa-soap-api/ShowStudents?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ShowStudentsService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/projektsoa-soap-api/ShowStudents?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ShowStudentsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ShowStudentsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShowStudentsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ShowStudentsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ShowStudentsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ShowStudentsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ShowStudents
     */
    @WebEndpoint(name = "ShowStudentsPort")
    public ShowStudents getShowStudentsPort() {
        return super.getPort(ShowStudentsPort, ShowStudents.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShowStudents
     */
    @WebEndpoint(name = "ShowStudentsPort")
    public ShowStudents getShowStudentsPort(WebServiceFeature... features) {
        return super.getPort(ShowStudentsPort, ShowStudents.class, features);
    }

}
