package pl.edu.agh.kis.manage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2021-05-05T07:19:45.213+02:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "http://kis.edu.agh.pl/", name = "ManageStudents")
@XmlSeeAlso({ObjectFactory.class})
public interface ManageStudents {

    @WebMethod(action = "deleteStudent")
    @RequestWrapper(localName = "delStudent", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.edu.agh.kis.DelStudent")
    @ResponseWrapper(localName = "delStudentResponse", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.edu.agh.kis.DelStudentResponse")
    @WebResult(name = "result", targetNamespace = "")
    public pl.edu.agh.kis.manage.Student delStudent(

        @WebParam(name = "index", targetNamespace = "")
        java.lang.String index
    );

    @WebMethod(action = "modifyStudent")
    @RequestWrapper(localName = "modStudent", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.edu.agh.kis.ModStudent")
    @ResponseWrapper(localName = "modStudentResponse", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.edu.agh.kis.ModStudentResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.util.List<pl.edu.agh.kis.manage.Student> modStudent(

        @WebParam(name = "index", targetNamespace = "")
        java.lang.String index,
        @WebParam(name = "field", targetNamespace = "")
        java.lang.String field,
        @WebParam(name = "value", targetNamespace = "")
        java.lang.String value
    );

    @WebMethod(action = "addStudent")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.edu.agh.kis.AddStudent")
    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://kis.edu.agh.pl/", className = "pl.edu.agh.kis.AddStudentResponse")
    @WebResult(name = "result", targetNamespace = "")
    public pl.edu.agh.kis.manage.Student addStudent(

        @WebParam(name = "firstName", targetNamespace = "")
        java.lang.String firstName,
        @WebParam(name = "lastName", targetNamespace = "")
        java.lang.String lastName,
        @WebParam(name = "index", targetNamespace = "")
        java.lang.String index,
        @WebParam(name = "birthdate", targetNamespace = "")
        java.lang.String birthdate,
        @WebParam(name = "courses", targetNamespace = "")
        java.lang.String courses
    );
}
