package pl.edu.agh.kis.manage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2021-05-05T07:19:45.261+02:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "ManageStudentsService",
                  wsdlLocation = "http://localhost:8080/projektsoa-soap-api/ManageStudents?wsdl",
                  targetNamespace = "http://kis.edu.agh.pl/")
public class ManageStudentsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://kis.edu.agh.pl/", "ManageStudentsService");
    public final static QName ManageStudentsPort = new QName("http://kis.edu.agh.pl/", "ManageStudentsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/projektsoa-soap-api/ManageStudents?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ManageStudentsService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/projektsoa-soap-api/ManageStudents?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ManageStudentsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ManageStudentsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManageStudentsService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ManageStudentsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ManageStudentsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ManageStudentsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ManageStudents
     */
    @WebEndpoint(name = "ManageStudentsPort")
    public ManageStudents getManageStudentsPort() {
        return super.getPort(ManageStudentsPort, ManageStudents.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageStudents
     */
    @WebEndpoint(name = "ManageStudentsPort")
    public ManageStudents getManageStudentsPort(WebServiceFeature... features) {
        return super.getPort(ManageStudentsPort, ManageStudents.class, features);
    }

}
